spring.datasource.url=jdbc:postgresql://localhost:5432/balanced_wellness
spring.datasource.username=postgres
spring.datasource.password=

# This line is magic. It tells Java to automatically build your SQL tables for you!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true